package edu.ucam.modelos;
// Generated 04-abr-2018 17:06:38 by Hibernate Tools 5.2.8.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.Entity;

/**
 * Post generated by hbm2java
 */
//@Entity
//@Table(name="post")
public class Post implements java.io.Serializable {
	//@Id
	//@Column(name="id")
	private Integer id;
	//@Column(name="administradores")
	private Administradores administradores;
	private Post post;
	//@Column(name="titulo")
	private String titulo;
	//@Column(name="html")
	private String html;
	//@Column(name="fecha")
	private Date fecha;
	private Set posts = new HashSet(0);

	public Post() {
	}

	public Post(Administradores administradores, Post post, String titulo, String html, Date fecha) {
		this.administradores = administradores;
		this.post = post;
		this.titulo = titulo;
		this.html = html;
		this.fecha = fecha;
	}

	public Post(Administradores administradores, Post post, String titulo, String html, Date fecha, Set posts) {
		this.administradores = administradores;
		this.post = post;
		this.titulo = titulo;
		this.html = html;
		this.fecha = fecha;
		this.posts = posts;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Administradores getAdministradores() {
		return this.administradores;
	}

	public void setAdministradores(Administradores administradores) {
		this.administradores = administradores;
	}

	public Post getPost() {
		return this.post;
	}

	public void setPost(Post post) {
		this.post = post;
	}

	public String getTitulo() {
		return this.titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	public String getHtml() {
		return this.html;
	}

	public void setHtml(String html) {
		this.html = html;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public Set getPosts() {
		return this.posts;
	}

	public void setPosts(Set posts) {
		this.posts = posts;
	}

}
